### Creating a new book
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "The Big lie",
  "author": "Joseph K",
  "publicationYear": 2023,
  "ISBN": 94633723546
}



### Get all books
GET http://localhost:3000/books

### Get one book by ID
GET http://localhost:3000/books/3

### Update a book by ID
PUT http://localhost:3000/books/3
Content-Type: application/json

{
  "title": "Build One Empower one",
  "author": "James k",
  "publicationYear": 2024,
  "ISBN": 234563756 
}



### Soft delete a book by ID
DELETE http://localhost:3000/books/soft/1

### Hard delete a book by ID
DELETE http://localhost:3000/books/3

### Count books by publication year
GET http://localhost:3000/books/count/2024


