### Creating a new book
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Dream Big",
  "author": "John Doe",
  "publicationYear": 1999,
  "ISBN": 9780201616224
}



### Get all books
GET http://localhost:3000/books

### Get one book by ID
GET http://localhost:3000/books/2

### Update a book by ID
PUT http://localhost:3000/books/15
Content-Type: application/json

{
  "title": "think big Updated",
  "author": "brian Doe",
  "publicationYear": 2001,
  "ISBN": 34547363776
}



### Soft delete a book by ID
DELETE http://localhost:3000/books/soft/1

### Hard delete a book by ID
DELETE http://localhost:3000/books/11

### Count books by publication year
GET http://localhost:3000/books/count/1999


